package agentd

import (
	"context"
	"log/slog"
	"runtime"
	"sync"
	"time"

	"github.com/spotter/spotter/internal/protocol"
	"github.com/spotter/spotter/internal/timefmt"
)

// SetAuditLogger attaches an AuditLogger to the agent. Called by
// cmd/agent after config load; nil disables audit persistence.
func (a *Agent) SetAuditLogger(al *AuditLogger) { a.audit = al }

// Config holds the agent's runtime settings.
type Config struct {
	DeviceID           string
	ListenAddr         string
	MulticastGroup     string
	AgentVersion       string
	EnablePowerActions bool          // opt-in: allow POST /api/v1/reboot & /shutdown
	EnableLogStream    bool          // opt-in: allow GET /api/v1/logs
	LogUnit            string        // journalctl -u unit name; default "spotterd.service"
	HelloInterval      time.Duration // proactive HELLO cadence; default 5s (see udp.go)
	Auth               AuthConfig    // opt-in: when Enabled, all non-/healthz endpoints demand Bearer token
	Server             ServerConfig  // server-level knobs (timeouts + rate limits)
	Logs               LogsConfig    // log streaming knobs (unit + tail clamps)
}

// AuthConfig is the [auth] TOML section. When Enabled is true the
// agent embeds {auth:{required:true}} into /api/v1/info responses
// and rejects unauthenticated callers from any other endpoint with
// 401. The token is a UUID v4 generated by install.sh and stored at
// /etc/spotterd/agent.toml with mode 0600.
type AuthConfig struct {
	Enabled bool
	Token   string
}

// HasToken reports whether Auth is configured with a non-empty token.
// Used by SetInfo to decide whether to embed Auth in the response.
func (a AuthConfig) HasToken() bool { return a.Enabled && a.Token != "" }

// ServerConfig is the [server] TOML section. Zero values map to
// the package defaults via fillDefaultsLocked in agent.go.
type ServerConfig struct {
	ReadTimeout        time.Duration
	WriteTimeout       time.Duration
	MaxHeaderBytes     int
	PowerActionRatePerS float64 // rate-limiter for POST /api/v1/{reboot,shutdown}; 0 = no limit
	LogStreamRatePerS   float64 // rate-limiter for GET /api/v1/logs; 0 = no limit
}

// LogsConfig is the [logs] TOML section. Unit defaults to
// "spotterd.service" if empty; tail clamps fire even when 0 (we fall
// to package-level defaultLogTail / maxLogTail).
type LogsConfig struct {
	Unit        string
	DefaultTail int
	MaxTail     int
}

// Agent owns the cached DeviceInfo and exposes it to the HTTP/UDP layers.
type Agent struct {
	cfg    Config
	logger *slog.Logger
	mu     sync.RWMutex
	info   protocol.DeviceInfo

	// collect re-collects DeviceInfo on demand. When set, every
	// /api/v1/info request runs a fresh collect so collected_at and
	// uptime_seconds track wall-clock between polls. Optional — when
	// nil, the agent serves the cached snapshot.
	collect func(ctx context.Context) (protocol.DeviceInfo, error)

	// limiter is the optional per-IP rate-limit bucket for power
	// actions / log streams. Allocated lazily inside Handler().
	limiter  *ipLimiter
	limOnce  sync.Once

	// audit persists every power dispatch to a TSV file the
	// operator can grep / forward to a SIEM. Optional — set by
	// the cmd/agent setup path.
	audit *AuditLogger
}

// New constructs an Agent. Returns an error if cfg is missing required fields.
func New(cfg Config, logger *slog.Logger) (*Agent, error) {
	if cfg.DeviceID == "" {
		return nil, errMissing("device_id")
	}
	if cfg.ListenAddr == "" {
		return nil, errMissing("listen_addr")
	}
	if logger == nil {
		logger = slog.Default()
	}
	return &Agent{cfg: cfg, logger: logger, info: protocol.DeviceInfo{
		SchemaVersion: protocol.SchemaVersion,
		DeviceID:      cfg.DeviceID,
		AgentVersion:  cfg.AgentVersion,
	}}, nil
}

// Config returns the agent's configuration.
func (a *Agent) Config() Config { return a.cfg }

// Logger returns the agent's logger.
func (a *Agent) Logger() *slog.Logger { return a.logger }

// SetInfo atomically replaces the cached DeviceInfo.
func (a *Agent) SetInfo(info protocol.DeviceInfo) {
	a.mu.Lock()
	defer a.mu.Unlock()
	info.SchemaVersion = protocol.SchemaVersion
	if info.AgentVersion == "" {
		info.AgentVersion = a.cfg.AgentVersion
	}
	// Reflect auth state in the public payload so v2+ clients learn
	// whether to prompt for a token before calling /reboot etc.
	if a.cfg.Auth.HasToken() {
		info.Auth = &protocol.AuthInfo{Required: true}
	} else {
		info.Auth = nil
	}
	info.LastHeartbeatAt = protocol.LastHeartbeatAt(timefmt.NowUTC())
	a.info = info
}

// SetCollector installs a function that re-collects DeviceInfo on every
// /api/v1/info request. nil disables on-demand collection and the
// handler falls back to the cached snapshot. Call before the HTTP server
// starts accepting requests.
func (a *Agent) SetCollector(fn func(ctx context.Context) (protocol.DeviceInfo, error)) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.collect = fn
}

// Info returns the cached DeviceInfo.
func (a *Agent) Info() protocol.DeviceInfo {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return a.info
}

// refreshInfo runs the installed collector (if any) and replaces the
// cached snapshot. Returns the new info on success. When no collector
// is installed, returns the cached snapshot unchanged.
func (a *Agent) refreshInfo(ctx context.Context) (protocol.DeviceInfo, error) {
	a.mu.RLock()
	collect := a.collect
	a.mu.RUnlock()
	if collect == nil {
		return a.Info(), nil
	}
	info, err := collect(ctx)
	if err != nil {
		return protocol.DeviceInfo{}, err
	}
	a.SetInfo(info)
	return info, nil
}

type missingFieldError struct{ field string }

func (e *missingFieldError) Error() string { return "agentd: missing field: " + e.field }
func errMissing(f string) error            { return &missingFieldError{f} }

// heartbeatInterval is how often the agent emits a "heartbeat" log line.
// Short enough that operators see the stream is alive without flooding
// the journal; long enough that the journal is not dominated by heartbeats.
const heartbeatInterval = 30 * time.Second

// runHeartbeat logs a startup heartbeat followed by a periodic one. The
// goal is to give GUI clients something to follow in an otherwise silent
// service so they can confirm the log stream is live. Exits when ctx is
// cancelled.
func (a *Agent) runHeartbeat(ctx context.Context) {
	start := time.Now()
	a.logger.Info("heartbeat",
		slog.String("phase", "start"),
		slog.String("device_id", a.cfg.DeviceID),
		slog.String("agent_version", a.cfg.AgentVersion),
	)
	ticker := time.NewTicker(heartbeatInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			a.logger.Info("heartbeat",
				slog.Duration("uptime", time.Since(start)),
				slog.Int("goroutines", runtime.NumGoroutine()),
			)
		}
	}
}
