import { useEffect, useState } from 'react';
import { Tooltip, Spin, Empty } from 'antd';
import { CheckCircleTwoTone, CloseCircleTwoTone, ClockCircleTwoTone } from '@ant-design/icons';
import { useI18n } from '../state/I18nContext';
// wailsjs bindings are auto-generated by `wails generate module`
// and live in frontend/wailsjs/. Until the next regen, the
// GetPowerAuditRecent function may not be present — fall back
// to a dynamic lookup so this component still typechecks on
// a clean checkout.
// eslint-disable-next-line @typescript-eslint/no-var-requires
import * as RegistryApp from '../../wailsjs/go/main/RegistryApp';

const GetPowerAuditRecent = (RegistryApp as unknown as {
  GetPowerAuditRecent: (deviceID: string, limit: number) => Promise<unknown>;
}).GetPowerAuditRecent;

export interface AuditEntry {
  at: string; // RFC3339
  action: string; // "reboot" | "shutdown"
  dry_run: boolean;
  request_id?: string;
  remote_addr?: string;
  result: string; // "scheduled" | "would_execute" | "running" | "cancelled" | "delayed-executed" | "error"
}

interface Props {
  deviceID: string;
  // Bumping `revision` triggers a refetch — used after the
  // operator runs a power action.
  revision: number;
  // limit=0 means "use the server default (50)"; otherwise the
  // requested count is forwarded as ?limit=N.
  limit?: number;
}

// PowerAuditList fetches /api/v1/power/audit/recent?device=...&limit=...
// and renders a vertical timeline. Renders 503 / network errors
// as a single muted line so the user sees "no recent activity"
// rather than a broken pane.
export default function PowerAuditList({ deviceID, revision, limit }: Props) {
  const { t } = useI18n();
  const [entries, setEntries] = useState<AuditEntry[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setEntries(null);
    setError(null);
    GetPowerAuditRecent(deviceID, limit ?? 0)
      .then((resp: unknown) => {
        if (cancelled) return;
        // Wails serialises Go map[string]any as { entries, count }.
        const list = (resp as { entries?: AuditEntry[] })?.entries ?? [];
        setEntries(list);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(String((err as { message?: string })?.message ?? err));
      });
    return () => { cancelled = true; };
  }, [deviceID, revision, limit]);

  if (error) {
    return (
      <div style={{ color: 'var(--text-secondary)', fontSize: 12 }}>
        {t('detail.audit.error') || 'Audit log unavailable'}
      </div>
    );
  }
  if (entries === null) {
    return <Spin size="small" />;
  }
  if (entries.length === 0) {
    return <Empty
      image={Empty.PRESENTED_IMAGE_SIMPLE}
      description={t('detail.audit.empty') || 'No power actions recorded yet'}
      style={{ margin: 0 }}
    />;
  }

  return (
    <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
      {entries.map((e, i) => (
        <AuditRow key={`${e.at}-${i}`} entry={e} />
      ))}
    </ul>
  );
}

function AuditRow({ entry }: { entry: AuditEntry }) {
  const { t } = useI18n();
  const ago = relativeTime(entry.at);
  const isError = entry.result === 'error';
  const isSuccess = entry.result === 'scheduled' ||
    entry.result === 'would_execute' ||
    entry.result === 'delayed-executed';
  const isPending = entry.result === 'running';
  const icon = isError
    ? <CloseCircleTwoTone twoToneColor="#b71c1c" />
    : isPending
      ? <ClockCircleTwoTone twoToneColor="#faad14" />
      : <CheckCircleTwoTone twoToneColor="#52c41a" />;
  const actionLabel = entry.action === 'reboot'
    ? t('detail.audit.action.reboot') || 'Reboot'
    : t('detail.audit.action.shutdown') || 'Shutdown';
  const dryTag = entry.dry_run ? ` (${t('detail.audit.dryRun') || 'dry-run'})` : '';
  return (
    <li
      style={{
        display: 'flex', alignItems: 'center', gap: 8,
        padding: '4px 0', borderBottom: '1px solid var(--border)',
        fontSize: 12,
      }}
    >
      {icon}
      <span style={{ flex: 1, color: 'var(--text-primary)' }}>
        {actionLabel}{dryTag}
      </span>
      <Tooltip title={new Date(entry.at).toLocaleString()}>
        <span style={{ color: 'var(--text-secondary)' }}>{ago}</span>
      </Tooltip>
      <span style={{
        color: isError ? '#b71c1c' : 'var(--text-secondary)',
        marginLeft: 4, minWidth: 80, textAlign: 'right',
      }}>
        {resultLabel(t, entry.result)}
      </span>
    </li>
  );
}

function resultLabel(t: (k: string) => string, result: string): string {
  const map: Record<string, string> = {
    'scheduled': t('detail.audit.result.scheduled') || 'scheduled',
    'would_execute': t('detail.audit.result.would_execute') || 'would_execute',
    'running': t('detail.audit.result.running') || 'running',
    'cancelled': t('detail.audit.result.cancelled') || 'cancelled',
    'delayed-executed': t('detail.audit.result.delayed-executed') || 'executed',
    'error': t('detail.audit.result.error') || 'error',
  };
  return map[result] || result;
}

function relativeTime(iso: string): string {
  const t = new Date(iso).getTime();
  const now = Date.now();
  const diff = Math.max(0, now - t);
  const sec = Math.floor(diff / 1000);
  if (sec < 60) return `${sec}s`;
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h`;
  const day = Math.floor(hr / 24);
  return `${day}d`;
}
